[package]
name = "bevy_erm"
version = "0.2.0"
edition = "2021"

[dependencies]
# bevy = { version = "*", default-features = false, features = ["dynamic_linking"] }
bevy = { version = "*", default-features = true }